#this is the file which kubernetes cluster is created from
- name: generate cluster configuration from template which is used to install k8s
  template:
    src: "{{ role_path }}/files/kubekey/kube-cluster.yml.j2"
    dest: "{{ role_path }}/files/kubekey/kube-cluster.yaml"
  delegate_to: localhost
  become: false
#for sake of time whole file is uploaded and it will be downloadble easily
- name: download kubekey core files (tuned for 1.28.0) ver
  ansible.builtin.get_url:
    url: "https://back.sivanland.com/public/upload/img/2021/12/2/kubekey.tar.gz"
    dest: "/root/kubekey.tar.gz"
    owner: root
    group: root
    mode: "0644"
    force: no
    timeout: 60
  register: kubekey_dl
  when: hostvars['localhost'].kubekeys[inventory_hostname].master | default(false)
#downloaded file will be extracted
- name: untar downloaded file
  ansible.builtin.command: tar -xzf /root/kubekey.tar.gz -C /root
  when: hostvars['localhost'].kubekeys[inventory_hostname].master | default(false)
#here the file of the kubernetes cluster config copied
- name: copy created template kube-cluster.yaml to server (overwrite if exists)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/kubekey/kube-cluster.yaml"
    dest: /root/kubekey/kube-cluster.yaml
    owner: root
    group: root
    mode: '0644'
    force: yes
    backup: yes
  when: hostvars['localhost'].kubekeys[inventory_hostname].master | default(false)